### ISSUE TITLE
Release.pl and copying from Windows to Linux

### ISSUE THREAD

**Issue by keenanlang** [epics-modules/xxx#10]
Per Tim Mooney

>Some of you probably already knew this, but if you copy a RELEASE file from Windows to Linux, release.pl will be mightily confused by it.  I guess the CRLF messes things up, but I didn't bother to run it to ground.

**Comment by kmpeters** [comment]
Is the plan to modify release.pl to handle both line endings?

**Comment by keenanlang** [comment]
Took a look at this, assuming carriage returns are the issue,

    $line =~ s/\r//g;

after the chomp should do the trick.

**Comment by keenanlang** [comment]
Change made in 5a4d54c
