### ISSUE TITLE
areaDetector's CONFIG_SITE overrides CHECK_RELEASE

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/xxx#11]
xxx/configure/CONFIG_SITE sets CHECK_RELEASE:
https://github.com/epics-modules/xxx/blob/5a4d54cb80afe428692d7e3621be973b0ec7ddcc/configure/CONFIG_SITE#L19
And later include's areaDetector's CONFIG_SITE:
https://github.com/epics-modules/xxx/blob/5a4d54cb80afe428692d7e3621be973b0ec7ddcc/configure/CONFIG_SITE#L40
Which also sets CHECK_RELEASE:
https://github.com/areaDetector/areaDetector/blob/a29a631173ea0fb4807a3f47b40519a6a2f5b0a7/configure/CONFIG_SITE#L17

This isn't a problem with the default values, but setting CHECK_RELEASE=WARN for an IOC is very common.  A simple solution would be to set CHECK_RELEASE in xxx's CONFIG_SITE after areaDetector's CONFIG_SITE.

**Comment by keenanlang** [comment]
Fixed in  ca47af9
