### ISSUE TITLE
start_MEDM_xxx script does not use the default screen

### ISSUE THREAD

**Issue by prjemian** [epics-modules/xxx#21]
The `start_MEDM_xxx` shell script is hard-coded to use the `xxx.adl` screen.  Since there is code to use a screen defined in an environment variable (`DEFAULT_UI_FILE`), that env var should be used instead.

**Comment by prjemian** [comment]
follow as done in `start_caQtDM_xxx` shell script

**Comment by prjemian** [comment]
That is: `${1:-${DEFAULT_UI_FILE}}`

**Comment by timmmooney** [comment]
This was already addressed by changes in changePrefix.


Tim Mooney (mooney@anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________
