### ISSUE TITLE
st.cmd.* has hard coded IOC name

### ISSUE THREAD

**Issue by prjemian** [epics-modules/xxx#28]
When using the XXX module as an IOC template, it is easy to change the IOC prefix in one place: `common.iocsh`.  However, the `st.cmd.*` files use a hard-coded `IOC=xxx` definition.

This should use `IOC=$(PREFIX)` instead.

**Comment by keenanlang** [comment]
Fixed with #31

**Comment by prjemian** [comment]
fixed by #31
