### ISSUE TITLE
xxx does not build with recent versions of areaDetector

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/xxx#4]
There are issues with building xxx with areaDetector.  areaDetector has optional dependencies on external libraries (HDF5, OPENCV, EPICS-V4, etc.) that are not correctly captured by the synApps/support/configure synApps/support/CONFIG_SITE, and xxx/configure/RELEASE and xxx/xxxApp/src/Makefile.  

I have modified the dxp/configure/RELEASE and quadEM/configure/RELEASE so they optionally include the areaDetector/configure/RELEASE_PATHS.local and RELEASE_PRODS.local so they will properly build with the configuration defined in areaDetector/configure.  Something similar needs to be done for xxx.

**Comment by keenanlang** [comment]
Fixed with commit e2828dc3e30933cf2cbfd54d796cc81ea18a3b49
