### ISSUE TITLE
Where is the IOC macro defined?

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/xxx#44]
The ``IOC`` macro is referenced here:

https://github.com/epics-modules/xxx/blob/093bc014a760bfc6e5e0ff7eb436cb8ba1d086cf/iocBoot/iocxxx/settings.iocsh#L2

Where is ``IOC`` defined?

**Comment by keenanlang** [comment]
IOC is defined in envPaths

**Comment by kmpeters** [comment]
Thanks.
