### ISSUE TITLE
motor ui files now have autoconvert subdirectory

### ISSUE THREAD

**Issue by prjemian** [epics-modules/xxx#5]
With [motor PR 72](https://github.com/epics-modules/motor/pull/72), the caQtDM screens directory now also has a [subdirectory](https://github.com/epics-modules/motor/pull/72#issuecomment-324672302).

Adjust the caQtDM starter scripts to include both directories with `ui/autoconvert/` coming after `ui/`.

**Comment by timmmooney** [comment]
That was done on 8/9.
