### ISSUE TITLE
Building vxWorks-only modules on Linux

### ISSUE THREAD

**Issue by frankdeath** [epics-modules/xxx#54]
Does it make sense to build the following modules on Linux? 

https://github.com/epics-modules/xxx/blob/265e1ec91a67b5f12f8ae1881a9cae50307483fd/xxxApp/src/Makefile#L378-L396

Most (all?) of the support in those modules is for VME-based hardware.

**Comment by frankdeath** [comment]
They've been included for many years:

https://github.com/epics-modules/xxx/commit/18859142c7a191cbdde30e4e5240e09d18ef1a2c

**Comment by kmpeters** [comment]
This is not an issue.
